#!/bin/bash  
#chkconfig: 2345 90 07
#description: hadoop zkfc service

RETVAL=0
# Source hadoop environment service
. /home/hadoop/.bashrc
start(){
    su hadoop -c "$HADOOP_PREFIX/sbin/hadoop-daemon.sh start zkfc"
}
stop(){
    su hadoop -c "$HADOOP_PREFIX/sbin/hadoop-daemon.sh stop zkfc"
}

case $1 in
start)
    start
;;
stop)
    stop
;;
esac
exit $RETVAL

