#!/bin/bash  
#chkconfig: 2345 81 09
#description: hadoop namenode service

RETVAL=0
# Source hadoop environment service
. /home/hadoop/.bashrc
start(){
    su hadoop -c "$HADOOP_PREFIX/sbin/hadoop-daemon.sh start journalnode"
}
stop(){
    su hadoop -c "$HADOOP_PREFIX/sbin/hadoop-daemon.sh stop journalnode"
}

case $1 in
start)
    start
;;
stop)
    stop
;;
esac
exit $RETVAL

