#!/bin/bash  
#chkconfig: 2345 99 01
#description: hbase master service

RETVAL=0
# Source hadoop environment service
. /home/hbase/.bashrc
start(){
    su hbase -c "$HBASE_HOME/bin/hbase-daemon.sh start regionserver"
}
stop(){
    su hbase -c "$HBASE_HOME/bin/hbase-daemon.sh stop regionserver"
}

case $1 in
start)
    start
;;
stop)
    stop
;;
esac
exit $RETVAL

